module stationServerIDL {

	struct Upcasted_Record{
		string RecordID;
		string lastName;
		string firstName;
		string status;
		string description;
		string address;
		string lastDate;
		string lastLocation;
	};
	
		
	interface StationInterface{
		boolean createCRecord(in string badgeId, in string firstName, in string lastName, in string description, in string status);
	
		boolean createMRecord(in string badgeId, in string firstName, in string lastName, in string address, in string lastDate, in string lastLocation, in string status);
	
		string getRecordCounts(in string badgeId);
	
		boolean editCRecord(in string badgeId, in string lastName, in string recordID, in string status);
	
		boolean transferRecord(in string badgeID, in string recordID, in string remoteStationServerName);
			
		boolean transfer(in Upcasted_Record theRecord);
	};
};
