package c6231;

/**
 * c6231/_StationInterfaceImplBase.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Station.idl Thursday, October 24, 2013 2:04:03
 * PM EDT
 */
public abstract class _StationInterfaceImplBase extends org.omg.CORBA.portable.ObjectImpl
        implements c6231.StationInterface, org.omg.CORBA.portable.InvokeHandler {

    // Constructors
    public _StationInterfaceImplBase() {
    }
    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("createCRecord", new java.lang.Integer(0));
        _methods.put("createMRecord", new java.lang.Integer(1));
        _methods.put("getRecordCounts", new java.lang.Integer(2));
        _methods.put("editCRecord", new java.lang.Integer(3));
        _methods.put("transferRecord", new java.lang.Integer(4));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
        if (__method == null) {
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        switch (__method.intValue()) {
            case 0: // c6231/StationInterface/createCRecord
            {
                String firstName = in.read_string();
                String lastName = in.read_string();
                String description = in.read_string();
                String status = in.read_string();
                String $result = null;
                $result = this.createCRecord(firstName, lastName, description, status);
                out = $rh.createReply();
                out.write_string($result);
                break;
            }

            case 1: // c6231/StationInterface/createMRecord
            {
                String firstName = in.read_string();
                String lastName = in.read_string();
                String address = in.read_string();
                String lastDate = in.read_string();
                String lastLocation = in.read_string();
                String status = in.read_string();
                String $result = null;
                $result = this.createMRecord(firstName, lastName, address, lastDate, lastLocation, status);
                out = $rh.createReply();
                out.write_string($result);
                break;
            }

            case 2: // c6231/StationInterface/getRecordCounts
            {
                String $result = null;
                $result = this.getRecordCounts();
                out = $rh.createReply();
                out.write_string($result);
                break;
            }

            case 3: // c6231/StationInterface/editCRecord
            {
                String lastName = in.read_string();
                String recordID = in.read_string();
                String newStatus = in.read_string();
                String $result = null;
                $result = this.editCRecord(lastName, recordID, newStatus);
                out = $rh.createReply();
                out.write_string($result);
                break;
            }

            case 4: // c6231/StationInterface/transferRecord
            {
                String badgeID = in.read_string();
                String recordID = in.read_string();
                String remoteStationServerName = in.read_string();
                String $result = null;
                $result = this.transferRecord(badgeID, recordID, remoteStationServerName);
                out = $rh.createReply();
                out.write_string($result);
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke
    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:c6231/StationInterface:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }
} // class _StationInterfaceImplBase
