package c6231;

/**
 * c6231/_StationInterfaceStub.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Station.idl Thursday, October 24, 2013 2:04:03
 * PM EDT
 */
public class _StationInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements c6231.StationInterface {

    public String createCRecord(String firstName, String lastName, String description, String status) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("createCRecord", true);
            $out.write_string(firstName);
            $out.write_string(lastName);
            $out.write_string(description);
            $out.write_string(status);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return createCRecord(firstName, lastName, description, status);
        } finally {
            _releaseReply($in);
        }
    } // createCRecord

    public String createMRecord(String firstName, String lastName, String address, String lastDate, String lastLocation, String status) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("createMRecord", true);
            $out.write_string(firstName);
            $out.write_string(lastName);
            $out.write_string(address);
            $out.write_string(lastDate);
            $out.write_string(lastLocation);
            $out.write_string(status);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return createMRecord(firstName, lastName, address, lastDate, lastLocation, status);
        } finally {
            _releaseReply($in);
        }
    } // createMRecord

    public String getRecordCounts() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("getRecordCounts", true);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return getRecordCounts();
        } finally {
            _releaseReply($in);
        }
    } // getRecordCounts

    public String editCRecord(String lastName, String recordID, String newStatus) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("editCRecord", true);
            $out.write_string(lastName);
            $out.write_string(recordID);
            $out.write_string(newStatus);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return editCRecord(lastName, recordID, newStatus);
        } finally {
            _releaseReply($in);
        }
    } // editCRecord

    public String transferRecord(String badgeID, String recordID, String remoteStationServerName) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("transferRecord", true);
            $out.write_string(badgeID);
            $out.write_string(recordID);
            $out.write_string(remoteStationServerName);
            $in = _invoke($out);
            String $result = $in.read_string();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return transferRecord(badgeID, recordID, remoteStationServerName);
        } finally {
            _releaseReply($in);
        }
    } // transferRecord
    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:c6231/StationInterface:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(java.io.ObjectInputStream s) throws java.io.IOException {
        String str = s.readUTF();
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);
        try {
            org.omg.CORBA.Object obj = orb.string_to_object(str);
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            _set_delegate(delegate);
        } finally {
            orb.destroy();
        }
    }

    private void writeObject(java.io.ObjectOutputStream s) throws java.io.IOException {
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);
        try {
            String str = orb.object_to_string(this);
            s.writeUTF(str);
        } finally {
            orb.destroy();
        }
    }
} // class _StationInterfaceStub
