package c6231;

/**
 * c6231/StationInterface.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Station.idl Thursday, October 24, 2013 2:04:03
 * PM EDT
 */
public interface StationInterface extends StationInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface StationInterface
