package c6231;

/**
 * c6231/StationInterfaceOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Station.idl Thursday, October 24, 2013 2:04:03
 * PM EDT
 */
public interface StationInterfaceOperations {

    String createCRecord(String firstName, String lastName, String description, String status);

    String createMRecord(String firstName, String lastName, String address, String lastDate, String lastLocation, String status);

    String getRecordCounts();

    String editCRecord(String lastName, String recordID, String newStatus);

    String transferRecord(String badgeID, String recordID, String remoteStationServerName);
} // interface StationInterfaceOperations
