package c6231;

/**
 * c6231/StationInterfaceHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Station.idl Thursday, October 24, 2013 2:04:03
 * PM EDT
 */
public final class StationInterfaceHolder implements org.omg.CORBA.portable.Streamable {

    public c6231.StationInterface value = null;

    public StationInterfaceHolder() {
    }

    public StationInterfaceHolder(c6231.StationInterface initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = c6231.StationInterfaceHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        c6231.StationInterfaceHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return c6231.StationInterfaceHelper.type();
    }
}
